name: Automated CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: |
        pip install pyinstaller

    - name: Build Application
      run: |
        pyinstaller --onefile app.py

    - name: Install Advanced Installer
      run: |
        choco install advanced-installer --version=22.3 -y

    - name: Verify Advanced Installer Installation
      shell: cmd
      run: |
        IF NOT EXIST "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" (
          echo Error: Advanced Installer is not installed correctly.
          exit /b 1
        )

    - name: Configure and Build Installer
      shell: cmd
      run: |
        REM Debug: Output the current directory and list files
        echo Current Directory: %CD%
        dir %CD%

        REM Set variables
        SET APP_NAME=SimpleApp
        SET OUTPUT_DIR=%CD%\SimpleApp\Output
        SET DIST_DIR=%CD%\dist
        SET AIP_FILE=%CD%\%APP_NAME%Installer.aip

        REM Ensure output directory exists
        IF NOT EXIST "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"

        REM Debug: Check directories before proceeding
        echo DIST_DIR=%DIST_DIR%
        echo OUTPUT_DIR=%OUTPUT_DIR%

        REM Create new Advanced Installer project
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /new "%AIP_FILE%" /type exe

        REM Check if the AIP file was created
        IF NOT EXIST "%AIP_FILE%" (
          echo Error: Failed to create the AIP file at "%AIP_FILE%".
          exit /b 1
        )

        REM Set package name and output path
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetPackageName "%APP_NAME%.exe"
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetOutputPath "%OUTPUT_DIR%"

        REM Add application files to the installer
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /AddFolder "Application Folder" "%DIST_DIR%"

        REM Add desktop shortcut
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /AddShortcut Desktop "Application Folder\\%APP_NAME%.exe"

        REM Build the installer
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /build "%AIP_FILE%"

    - name: Upload Installer to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SimpleAppInstaller
        path: SimpleApp\Output\*

