name: Automated CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: |
        pip install pyinstaller

    - name: Build Application
      run: |
        pyinstaller --onefile app.py

    - name: Install Advanced Installer
      run: |
        choco install advanced-installer --version=22.3 -y

    - name: Verify Advanced Installer Installation
      shell: cmd
      run: |
        IF NOT EXIST "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" (
          echo Error: Advanced Installer is not installed correctly.
          exit /b 1
        )

    - name: Configure and Build Installer
      shell: cmd
      run: |
        REM Set variables
        SET APP_NAME=SimpleApp
        SET OUTPUT_DIR=%USERPROFILE%\Desktop\%APP_NAME%\Output
        SET DIST_DIR=%USERPROFILE%\Desktop\%APP_NAME%\dist
        SET AIP_FILE=%USERPROFILE%\Desktop\%APP_NAME%Installer.aip

        REM Ensure output and dist directories exist
        IF NOT EXIST "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"
        IF NOT EXIST "%DIST_DIR%" mkdir "%DIST_DIR%"

        REM Debugging paths
        echo APP_NAME=%APP_NAME%
        echo OUTPUT_DIR=%OUTPUT_DIR%
        echo DIST_DIR=%DIST_DIR%
        echo AIP_FILE=%AIP_FILE%

        REM Create a new Advanced Installer project
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /new "%AIP_FILE%" /type exe

        REM Check if the AIP file was created
        IF NOT EXIST "%AIP_FILE%" (
          echo Error: Failed to create the AIP file at "%AIP_FILE%".
          exit /b 1
        )

        REM Set package name and output path
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetPackageName "%APP_NAME%.exe"
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetOutputPath "%OUTPUT_DIR%"

        REM Add application files to the installer
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /edit "%AIP_FILE%" /AddFolder "Application Folder" "%DIST_DIR%"

        REM Build the installer
        "C:\Program Files (x86)\Caphyon\Advanced Installer 22.3\bin\x86\AdvancedInstaller.com" /build "%AIP_FILE%"

    - name: Upload Installer to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SimpleAppInstaller
        path: ${{ env.USERPROFILE }}\Desktop\SimpleApp\Output\*


