name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Python dependencies
    - name: Install Python Dependencies
      run: pip install pyinstaller

    # Step 4: Build the application with PyInstaller
    - name: Build Application with PyInstaller
      run: pyinstaller --onefile app.py

    # Step 5: Install Advanced Installer
    - name: Install Advanced Installer
      run: choco install advanced-installer --version=22.3 -y

    # Step 6: Define environment variables
    - name: Define Variables
      run: |
        echo OUTPUT_DIR=${{ github.workspace }}\\dist >> $GITHUB_ENV
        echo AIP_FILE=${{ github.workspace }}\\dist\\project.aip >> $GITHUB_ENV

    # Step 7: Debug Variables
    - name: Debug Variables
      run: |
        echo "AIP_FILE: ${{ env.AIP_FILE }}"
        echo "OUTPUT_DIR: ${{ env.OUTPUT_DIR }}"

    # Step 8: Create a new AIP project
    - name: Create New AIP Project
      run: |
        "C:\\Program Files (x86)\\Caphyon\\Advanced Installer 22.3\\bin\\x86\\AdvancedInstaller.com" /new "%AIP_FILE%" -type exe -overwrite
      env:
        AIP_FILE: ${{ env.AIP_FILE }}

    # Step 9: Configure and Build the Installer
    - name: Configure and Build the Installer
      run: |
        "C:\\Program Files (x86)\\Caphyon\\Advanced Installer 22.3\\bin\\x86\\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetPackageName "${{ github.repository }}.exe"
        "C:\\Program Files (x86)\\Caphyon\\Advanced Installer 22.3\\bin\\x86\\AdvancedInstaller.com" /edit "%AIP_FILE%" /SetOutputPath "%OUTPUT_DIR%"
        "C:\\Program Files (x86)\\Caphyon\\AdvancedInstaller.com" /build "%AIP_FILE%"
      env:
        OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
        AIP_FILE: ${{ env.AIP_FILE }}

    # Step 10: Upload the installer to GitHub artifacts
    - name: Upload Installer to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Installer
        path: ${{ env.OUTPUT_DIR }}\\*



